/***************************************************************************
 *
 *                      Pollex Mobile Platform
 *
 * Copyright (c) 2004 by Pollex Mobile Software Co., Ltd. 
 *                       All Rights Reserved 
 *
 * Module   : 
 *
 * Purpose  : 
 *
\**************************************************************************/
#ifndef _AB_RS_H_
#define _AB_RS_H_

#define IDS_CONTACTS                ML("Contacts")
#define IDS_GROUPS                  ML("Groups")
#define IDS_NORECORD                ML("No records")
#define IDS_OPEN                    ML("Open")
#define IDS_CALL                    ML("Call")
#define IDS_WRITE                   ML("Write message")
#define IDS_NEW                     ML("New contact")
#define IDS_EDIT                    ML("Edit")
#define IDS_DELETE                  ML("Delete")
#define IDS_DUPLICATE               ML("Duplicate")
#define IDS_SEND                    ML("Send contact")
#define IDS_COPYTOSIM               ML("Copy to SIM")
#define IDS_ABINFO                  ML("Addressbook info")
#define IDS_SIM                     ML("SIM Phonebook")
#define IDS_SERVICENO               ML("SIM service numbers")
#define IDS_SETTINGS                ML("Settings")
#define IDS_NEWGROUP                ML("New group")
#define IDS_SMS                     ML("SMS")
#define IDS_MMS                     ML("MMS")
#define IDS_DEFAULTS                ML("Defaults")
#define IDS_PHONENO                 ML("Phone number")
#define IDS_SMSNO                   ML("SMS number")
#define IDS_MMSNO                   ML("MMS number/address")
#define IDS_EMAILADDRESS            ML("E-mail address")
#define IDS_VIASMS                  ML("Via SMS")
#define IDS_VIAMMS					ML("Via MMS")
#define IDS_VIAEMAIL                ML("Via e-mail")
#define IDS_VIABLUETOOTH            ML("Via Bluetooth")
#define IDS_COPYTOCONTACTS          ML("Copy to contacts")
#define IDS_NEWSIM                  ML("New SIM contacts")
#define IDS_MYNO                    ML("My numbers")
#define IDS_NEWMYNO                 ML("New my number")
#define IDS_SIMDETAIL               ML("SIM details")
#define IDS_VIEWNO                  ML("View number")
#define IDS_SORTBY                  ML("Sort by (first name/last name)")
#define IDS_SENDMSG                 ML("Send message")
#define IDS_REMOVEFRMOGROUP         ML("Remove from group")
#define IDS_ADDMEMBER               ML("Add members")
#define IDS_SELECTMEMBER			ML("Select members")
#define IDS_SENDMSG                 ML("Send message")
#define IDS_EXIT                    ML("Exit")
#define IDS_FIRSTNAME               ML("First name")
#define IDS_LASTNAME                ML("Last name")
#define IDS_TEL                     ML("Telephone")
#define IDS_TELHOME                 ML("Tel.(home)")
#define IDS_TELWORK                 ML("Tel.(work)")
#define IDS_MOBILE                  ML("Mobile")
#define IDS_MOBILEHOME              ML("Mobile(home)")
#define IDS_MOBILEWORK              ML("Mobile(work)")
#define IDS_FAX                     ML("Fax")
#define IDS_PAGER                   ML("Pager")
#define IDS_EMAIL                   ML("E-mail")
#define IDS_EMAILWORK               ML("E-mail(work)")
#define IDS_EMAILHOME               ML("E-mail(home)")
#define IDS_POSTALADDRESS           ML("Postal address")
#define IDS_HTTPURL                 ML("HTTP URL")
#define IDS_JOBTITLE                ML("Job title")
#define IDS_COMPANY                 ML("Company")
#define IDS_COMPANYTEL              ML("Company tel.")
#define IDS_COMPANYADDRESS          ML("Company address")
#define IDS_DTMF                    ML("DTMF string")
#define IDS_DATE                    ML("Date")
#define IDS_NOTE                    ML("Note")
#define IDS_SAVE                    ML("Save")
#define IDS_CLEAR                   ML("Clear")
#define IDS_CLOSE                   ML("Close")
#define IDS_QUICKDIAL               ML("Quick dialing")
#define IDS_ADDFIELD                ML("Add field")
#define IDS_REMOVEFIELD             ML("Remove field")
#define IDS_SETPIC                  ML("Set picture")
#define IDS_SETTONE                 ML("Set tone")
#define IDS_NO                      ML("No")
#define IDS_YES                     ML("Yes")
#define IDS_REMOVED                 ML("Removed")
#define IDS_REMOVE                  ML("Remove")
#define IDS_BACK                    ML("Back")
#define IDS_ASSIGN                  ML("Assign")
#define IDS_EMPTY                   ML("empty")
#define IDS_RENAMEGROUP             ML("Rename group")
#define IDS_DELETEGROUP             ML("Delete group")
#define IDS_GROUPNAME               ML("Group name")
#define IDS_GROUPNAMETEMP           ML("Group %d")
#define IDS_DELGROUP                ML("Delete group")
#define IDS_CONTACTDELETED          ML("Contact deleted")
#define IDS_OK                      ML("Ok")
#define IDS_REMOVEMEMBER            ML("Remove member")
#define IDS_SIMINFO                 ML("SIM info")
#define IDS_NEWSIMCONTACT           ML("New SIM contact")
#define IDS_SIMNOTREADY             ML("Reading SIM card.Please wait...")
#define IDS_SIMCAPACITY             ML("SIM capacity:")
#define IDS_FREECAPACITY            ML("Free:")
#define IDS_USEDCAPACITY            ML("Used:")
#define IDS_NAME                    ML("Name")
#define IDS_NUMBER                  ML("Number")
#define IDS_SAVED                   ML("Saved")
#define IDS_DELETECONTACT           ML("Delete contact?")
#define IDS_MEMORYFULL              ML("Memory full")
#define IDS_NEWCONTACT              ML("New contact")
#define IDS_NOTALLOWED              ML("Not allowed")
#define IDS_CANCEL                  ML("Cancel")
#define IDS_SELECT                  ML("Select")
#define IDS_ALL                     ML("All")
#define IDS_DELETEMANY              ML("Delete many")
#define IDS_NOPHONENUMS             ML("No phone numbers")
#define IDS_NOPHONENUM              ML("No phone number")
#define IDS_NOPHONENUMOREMAIL       ML("No phone number or email address")
#define IDS_NOEMAIL                 ML("No email address")
#define IDS_DEFINENAME              ML("Define name")
#define IDS_GROUP                   ML("Group")
#define IDS_DELETED                 ML("Deleted")
#define IDS_SETGROUPTONE            ML("Set group tone")
#define IDS_REMOVEMANY              ML("Remove many")
#define IDS_UNNAMED                 ML("Unnamed")
#define IDS_NOPICTURE               ML("No picture")
#define IDS_DELETEALL               ML("Delete all?") 
#define IDS_REMOVEASSIGNMENT		ML("Remove assignment?")
#define IDS_CONTACTISEMPTY			ML("Contact list is empty")
#define IDS_TONECHANGED				ML("Tone changed")
#define IDS_SAVECONTACT				ML("Save contact?")
#define IDS_SAVECHANGES				ML("Save changes?")
#define IDS_DELETESELECT            ML("Delete selected contacts?")
#define IDS_COPY                    ML("Copy")
#define IDS_COPYING                 ML("Copyint to SIM...")
#define IDS_COPIED                  ML("Copied to SIM")
#define IDS_COPYALL                 ML("Copy all to SIM?")
#define IDS_BELONGOTHERS            ML("Some contacts will be removed from another group.Continue?")
#define IDS_REMOVEALL               ML("Remove all?")
#define IDS_REMOVESELECT            ML("Remove selected members?")
#define IDS_COPYALLTOCONTACTS       ML("Copy all to Contacts?")
#define IDS_COPYFROMSIM             ML("Copying from SIM...")
#define IDS_COPIEDTOCONTACTS        ML("Copied to Contacts")
#define IDS_TOOMANY                 ML("Too many")
#define IDS_DUPLICATECONTACT        ML("Duplicate contact")
#define IDS_SAVING                  ML("Saving...")
#define IDS_DELETING                ML("Deleting...")
#define IDS_VMNSET                  ML("Voice mailbox\r\n number set")
#define IDS_VOICEMAILBOX            ML("Voice mailbox")
#define IDS_REPLACE                 ML("Replace?")
#define IDS_CONTACTTONE             ML("Contact tone")
#define IDS_GROUPTONE               ML("Group tone")
#define IDS_MESSAGING               ML("Messaging")
#define IDS_REPLACED				ML("Replaced")
#define IDS_SELECTCONTACT			ML("Select contacts")
#define IDS_SELECTONECONTACT		ML("Select contact")
#define IDS_INSERT_SIM				ML("insert sim card")
#define IDS_RENAME_GROUP			ML("Rename group")
#define IDS_OPENING					ML("opening...")
#define IDS_MOVING					ML("moving")
#define IDS_REMOVING				ML("Removing")
#define IDS_FAILED					ML("Failed")
#endif // _AB_RS_H_
 
 
 
