/********************************************************************
  Copyright (C), 2004, IVT Corporation
  Module name:		sdk_def.h
  Author:       
  Version:        
  Date: 
  Abstract:   
  Revision History:        

********************************************************************/



#ifndef _SDK_DEF_H
#define _SDK_DEF_H

typedef char BTINT8;
typedef unsigned char BTUINT8;
typedef unsigned char BTBOOL;
typedef short BTINT16;
typedef unsigned short BTUINT16;
typedef long BTINT32;
typedef unsigned long BTUINT32;
typedef void * BTLPVOID;

typedef BTUINT32 BTDEVHDL;
typedef BTUINT32 BTSVCHDL;
typedef BTUINT32 BTCONNHDL;
typedef BTUINT32 BTSHCHDL;
typedef BTUINT32 BTSDKHANDLE;

#ifndef FUNC_EXPORT
#define FUNC_EXPORT 
#endif


#define BTSDK_TRUE		1
#define BTSDK_FALSE		0


/* Max size value used in service attribute structures */
#define BTSDK_SERVICENAME_MAXLENGTH				80
#define BTSDK_MAX_SUPPORT_FORMAT				6		/* OPP format number */
#define BTSDK_PATH_MAXLENGTH					256		/* Shall not be larger than FTP_MAX_PATH and OPP_MAX_PATH */
#define BTSDK_CARDNAME_MAXLENGTH				64		/* Shall not be larger than OPP_MAX_NAME */
#define BTSDK_PACKETTYPE_MAXNUM					10		/* PAN supported network packet type */

/* Max size value used in device attribute structures */
#define BTSDK_DEVNAME_LEN						64		/* Shall not be larger than MAX_NAME_LEN */
#define BTSDK_SHORTCUT_NAME_LEN					100
#define BTSDK_BDADDR_LEN						6
#define BTSDK_LINK_KEY_LENGTH					16
#define BTSDK_PIN_CODE_LEN						16

/* Invalid handle value for all handle type */
#define BTSDK_INVALID_HANDLE					0x00000000

/* Error Code List */
#define BTSDK_OK												0x0000

/* SDP error */
#define BTSDK_ER_SDP_INDEX										0x00C0
#define BTSDK_ER_SERVER_IS_ACTIVE								(BTSDK_ER_SDP_INDEX + 0x0000)
#define BTSDK_ER_NO_SERVICE										(BTSDK_ER_SDP_INDEX + 0x0001)
#define BTSDK_ER_SERVICE_RECORD_NOT_EXIST						(BTSDK_ER_SDP_INDEX + 0x0002)

/* General Error */
#define BTSDK_ER_GENERAL_INDEX									0x0300
#define BTSDK_ER_HANDLE_NOT_EXIST								(BTSDK_ER_GENERAL_INDEX + 0x0001)
#define BTSDK_ER_OPERATION_FAILURE								(BTSDK_ER_GENERAL_INDEX + 0x0002)
#define BTSDK_ER_SDK_UNINIT										(BTSDK_ER_GENERAL_INDEX + 0x0003)
#define BTSDK_ER_INVALID_PARAMETER								(BTSDK_ER_GENERAL_INDEX + 0x0004)
#define BTSDK_ER_NULL_POINTER									(BTSDK_ER_GENERAL_INDEX + 0x0005)
#define BTSDK_ER_NO_MEMORY										(BTSDK_ER_GENERAL_INDEX + 0x0006)
#define BTSDK_ER_BUFFER_NOT_ENOUGH								(BTSDK_ER_GENERAL_INDEX + 0x0007)
#define BTSDK_ER_FUNCTION_NOTSUPPORT							(BTSDK_ER_GENERAL_INDEX + 0x0008)
#define BTSDK_ER_NO_FIXED_PIN_CODE								(BTSDK_ER_GENERAL_INDEX + 0x0009)
#define BTSDK_ER_CONNECTION_EXIST								(BTSDK_ER_GENERAL_INDEX + 0x000A)
#define BTSDK_ER_OPERATION_CONFLICT								(BTSDK_ER_GENERAL_INDEX + 0x000B)
#define BTSDK_ER_NO_MORE_CONNECTION_ALLOWED						(BTSDK_ER_GENERAL_INDEX + 0x000C)
#define BTSDK_ER_ITEM_EXIST										(BTSDK_ER_GENERAL_INDEX + 0x000D)
#define BTSDK_ER_ITEM_INUSE										(BTSDK_ER_GENERAL_INDEX + 0x000E)
#define BTSDK_ER_DEVICE_UNPAIRED								(BTSDK_ER_GENERAL_INDEX + 0x000F)

/* HCI Error */
#define BTSDK_ER_HCI_INDEX										0x0400
#define BTSDK_ER_UNKNOWN_HCI_COMMAND							(BTSDK_ER_HCI_INDEX + 0x0001)
#define BTSDK_ER_NO_CONNECTION									(BTSDK_ER_HCI_INDEX + 0x0002)
#define BTSDK_ER_HARDWARE_FAILURE								(BTSDK_ER_HCI_INDEX + 0x0003)
#define BTSDK_ER_PAGE_TIMEOUT									(BTSDK_ER_HCI_INDEX + 0x0004)
#define BTSDK_ER_AUTHENTICATION_FAILURE							(BTSDK_ER_HCI_INDEX + 0x0005)
#define BTSDK_ER_KEY_MISSING									(BTSDK_ER_HCI_INDEX + 0x0006)
#define BTSDK_ER_MEMORY_FULL									(BTSDK_ER_HCI_INDEX + 0x0007)
#define BTSDK_ER_CONNECTION_TIMEOUT								(BTSDK_ER_HCI_INDEX + 0x0008)
#define BTSDK_ER_MAX_NUMBER_OF_CONNECTIONS						(BTSDK_ER_HCI_INDEX + 0x0009)
#define BTSDK_ER_MAX_NUMBER_OF_SCO_CONNECTIONS					(BTSDK_ER_HCI_INDEX + 0x000a)
#define BTSDK_ER_ACL_CONNECTION_ALREADY_EXISTS					(BTSDK_ER_HCI_INDEX + 0x000b)
#define BTSDK_ER_COMMAND_DISALLOWED								(BTSDK_ER_HCI_INDEX + 0x000c)
#define BTSDK_ER_HOST_REJECTED_LIMITED_RESOURCES				(BTSDK_ER_HCI_INDEX + 0x000d)
#define BTSDK_ER_HOST_REJECTED_SECURITY_REASONS					(BTSDK_ER_HCI_INDEX + 0x000e)
#define BTSDK_ER_HOST_REJECTED_PERSONAL_DEVICE					(BTSDK_ER_HCI_INDEX + 0x000f)
#define BTSDK_ER_HOST_TIMEOUT									(BTSDK_ER_HCI_INDEX + 0x0010)
#define BTSDK_ER_UNSUPPORTED_FEATURE							(BTSDK_ER_HCI_INDEX + 0x0011)
#define BTSDK_ER_INVALID_HCI_COMMAND_PARAMETERS					(BTSDK_ER_HCI_INDEX + 0x0012)
#define BTSDK_ER_PEER_DISCONNECTION_USER_END					(BTSDK_ER_HCI_INDEX + 0x0013)
#define BTSDK_ER_PEER_DISCONNECTION_LOW_RESOURCES				(BTSDK_ER_HCI_INDEX + 0x0014)
#define BTSDK_ER_PEER_DISCONNECTION_TO_POWER_OFF				(BTSDK_ER_HCI_INDEX + 0x0015)
#define BTSDK_ER_LOCAL_DISCONNECTION							(BTSDK_ER_HCI_INDEX + 0x0016)
#define BTSDK_ER_REPEATED_ATTEMPTS								(BTSDK_ER_HCI_INDEX + 0x0017)
#define BTSDK_ER_PAIRING_NOT_ALLOWED							(BTSDK_ER_HCI_INDEX + 0x0018)
#define BTSDK_ER_UNKNOWN_LMP_PDU								(BTSDK_ER_HCI_INDEX + 0x0019)
#define BTSDK_ER_UNSUPPORTED_REMOTE_FEATURE						(BTSDK_ER_HCI_INDEX + 0x001a)
#define BTSDK_ER_SCO_OFFSET_REJECTED							(BTSDK_ER_HCI_INDEX + 0x001b)
#define BTSDK_ER_SCO_INTERVAL_REJECTED							(BTSDK_ER_HCI_INDEX + 0x001c)
#define BTSDK_ER_SCO_AIR_MODE_REJECTED							(BTSDK_ER_HCI_INDEX + 0x001d)
#define BTSDK_ER_INVALID_LMP_PARAMETERS							(BTSDK_ER_HCI_INDEX + 0x001e)
#define BTSDK_ER_UNSPECIFIED_ERROR								(BTSDK_ER_HCI_INDEX + 0x001f)
#define BTSDK_ER_UNSUPPORTED_LMP_PARAMETER_VALUE				(BTSDK_ER_HCI_INDEX + 0x0020)
#define BTSDK_ER_ROLE_CHANGE_NOT_ALLOWED						(BTSDK_ER_HCI_INDEX + 0x0021)
#define BTSDK_ER_LMP_RESPONSE_TIMEOUT							(BTSDK_ER_HCI_INDEX + 0x0022)
#define BTSDK_ER_LMP_ERROR_TRANSACTION_COLLISION				(BTSDK_ER_HCI_INDEX + 0x0023)
#define BTSDK_ER_LMP_PDU_NOT_ALLOWED							(BTSDK_ER_HCI_INDEX + 0x0024)
#define BTSDK_ER_ENCRYPTION_MODE_NOT_ACCEPTABLE					(BTSDK_ER_HCI_INDEX + 0x0025)
#define BTSDK_ER_UNIT_KEY_USED									(BTSDK_ER_HCI_INDEX + 0x0026)
#define BTSDK_ER_QOS_IS_NOT_SUPPORTED							(BTSDK_ER_HCI_INDEX + 0x0027)
#define BTSDK_ER_INSTANT_PASSED									(BTSDK_ER_HCI_INDEX + 0x0028)
#define BTSDK_ER_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED			(BTSDK_ER_HCI_INDEX + 0x0029)

/* CTP/ICP error */
#define BTSDK_ER_CTP_INDEX										0x0500
#define BTSDK_ER_CTP_GW_EXIST									(BTSDK_ER_CTP_INDEX + 0x0000)	
#define BTSDK_ER_CTP_GW_NONEXIST								(BTSDK_ER_CTP_INDEX + 0x0001)
#define BTSDK_ER_USER_HANGUP									(BTSDK_ER_CTP_INDEX + 0x0002)
#define BTSDK_ER_REMOTE_HANGUP									(BTSDK_ER_CTP_INDEX + 0x0003)

/* OBEX error */
#define BTSDK_ER_OBEX_INDEX										0x0600
#define BTSDK_ER_CONTINUE										(BTSDK_ER_OBEX_INDEX + 0x0090)
#define BTSDK_ER_SUCCESS										(BTSDK_ER_OBEX_INDEX + 0x00A0)
#define BTSDK_ER_CREATED										(BTSDK_ER_OBEX_INDEX + 0x00A1)
#define BTSDK_ER_ACCEPTED										(BTSDK_ER_OBEX_INDEX + 0x00A2)
#define BTSDK_ER_NON_AUTH_INFO									(BTSDK_ER_OBEX_INDEX + 0x00A3)
#define BTSDK_ER_NO_CONTENT										(BTSDK_ER_OBEX_INDEX + 0x00A4)
#define BTSDK_ER_RESET_CONTENT									(BTSDK_ER_OBEX_INDEX + 0x00A5)
#define BTSDK_ER_PARTIAL_CONTENT								(BTSDK_ER_OBEX_INDEX + 0x00A6)
#define BTSDK_ER_MULT_CHOICES									(BTSDK_ER_OBEX_INDEX + 0x00B0)
#define BTSDK_ER_MOVE_PERM										(BTSDK_ER_OBEX_INDEX + 0x00B1)
#define BTSDK_ER_MOVE_TEMP										(BTSDK_ER_OBEX_INDEX + 0x00B2)
#define BTSDK_ER_SEE_OTHER										(BTSDK_ER_OBEX_INDEX + 0x00B3)
#define BTSDK_ER_NOT_MODIFIED									(BTSDK_ER_OBEX_INDEX + 0x00B4)
#define BTSDK_ER_USE_PROXY										(BTSDK_ER_OBEX_INDEX + 0x00B5)
#define BTSDK_ER_BAD_REQUEST									(BTSDK_ER_OBEX_INDEX + 0x00C0)
#define BTSDK_ER_UNAUTHORIZED									(BTSDK_ER_OBEX_INDEX + 0x00C1)
#define BTSDK_ER_PAY_REQ										(BTSDK_ER_OBEX_INDEX + 0x00C2)
#define BTSDK_ER_FORBIDDEN										(BTSDK_ER_OBEX_INDEX + 0x00C3)
#define BTSDK_ER_NOTFOUND										(BTSDK_ER_OBEX_INDEX + 0x00C4)
#define BTSDK_ER_METHOD_NOT_ALLOWED								(BTSDK_ER_OBEX_INDEX + 0x00C5)
#define BTSDK_ER_NOT_ACCEPTABLE									(BTSDK_ER_OBEX_INDEX + 0x00C6)
#define BTSDK_ER_PROXY_AUTH_REQ									(BTSDK_ER_OBEX_INDEX + 0x00C7)
#define BTSDK_ER_REQUEST_TIMEOUT								(BTSDK_ER_OBEX_INDEX + 0x00C8)
#define BTSDK_ER_CONFLICT										(BTSDK_ER_OBEX_INDEX + 0x00C9)
#define BTSDK_ER_GONE											(BTSDK_ER_OBEX_INDEX + 0x00CA)
#define BTSDK_ER_LEN_REQ										(BTSDK_ER_OBEX_INDEX + 0x00CB)
#define BTSDK_ER_PREC_FAIL										(BTSDK_ER_OBEX_INDEX + 0x00CC)
#define BTSDK_ER_REQ_ENTITY_TOO_LARGE							(BTSDK_ER_OBEX_INDEX + 0x00CD)
#define BTSDK_ER_URL_TOO_LARGE									(BTSDK_ER_OBEX_INDEX + 0x00CE)
#define BTSDK_ER_UNSUPPORTED_MEDIA_TYPE							(BTSDK_ER_OBEX_INDEX + 0x00CF)
#define BTSDK_ER_SVR_ERR										(BTSDK_ER_OBEX_INDEX + 0x00D0)
#define BTSDK_ER_NOTIMPLEMENTED									(BTSDK_ER_OBEX_INDEX + 0x00D1)
#define BTSDK_ER_BAD_GATEWAY									(BTSDK_ER_OBEX_INDEX + 0x00D2)
#define BTSDK_ER_SERVICE_UNAVAILABLE							(BTSDK_ER_OBEX_INDEX + 0x00D3)
#define BTSDK_ER_GATEWAY_TIMEOUT								(BTSDK_ER_OBEX_INDEX + 0x00D4)
#define BTSDK_ER_HTTP_NOTSUPPORT								(BTSDK_ER_OBEX_INDEX + 0x00D5)
#define BTSDK_ER_DATABASE_FULL									(BTSDK_ER_OBEX_INDEX + 0x00E0)
#define BTSDK_ER_DATABASE_LOCK									(BTSDK_ER_OBEX_INDEX + 0x00E1)

/* Serial wrap error*/ 
#define BTSDK_ER_SWRAPINDX										0X0700
#define BTSDK_ER_COM_INUSED										(BTSDK_ER_SWRAPINDX + 0x0001)
#define BTSDK_ER_COM_OPENNOTCOMPLETED							(BTSDK_ER_SWRAPINDX + 0x0002)

/* APP extended error base */
#define BTSDK_ER_APPEXTEND_INDEX								0x4000


/* Class of Device */
/*major service classes*/
#define BTSDK_SRVCLS_LDM						0x002000
#define BTSDK_SRVCLS_POSITION					0x010000
#define BTSDK_SRVCLS_NETWORK					0x020000
#define BTSDK_SRVCLS_RENDER						0x040000
#define BTSDK_SRVCLS_CAPTURE					0x080000
#define BTSDK_SRVCLS_OBJECT						0x100000
#define BTSDK_SRVCLS_AUDIO						0x200000
#define BTSDK_SRVCLS_TELEPHONE					0x400000
#define BTSDK_SRVCLS_INFOR						0x800000
#define BTSDK_SRVCLS_MASK(a)					(((BTUINT32)(a) >> 13) & 0x7FF)

/*major device classes*/			                                    
#define BTSDK_DEVCLS_MISC						0x000000
#define BTSDK_DEVCLS_COMPUTER					0x000100
#define BTSDK_DEVCLS_PHONE						0x000200
#define BTSDK_DEVCLS_LAP						0x000300
#define BTSDK_DEVCLS_AUDIO						0x000400
#define BTSDK_DEVCLS_PERIPHERAL					0x000500
#define BTSDK_DEVCLS_IMAGE             			0x000600
#define BTSDK_DEVCLS_UNCLASSIFIED				0x001F00
#define BTSDK_DEVCLS_MASK(a)					(((BTUINT32)(a) >> 8) & 0x1F)
#define BTSDK_MINDEVCLS_MASK(a)					(((BTUINT32)(a) >> 2) & 0x3F)

/*the minor device class field - computer major class */
#define BTSDK_COMPCLS_UNCLASSIFIED				(BTSDK_DEVCLS_COMPUTER | 0x000000) 
#define BTSDK_COMPCLS_DESKTOP					(BTSDK_DEVCLS_COMPUTER | 0x000004)
#define BTSDK_COMPCLS_SERVER            		(BTSDK_DEVCLS_COMPUTER | 0x000008)
#define BTSDK_COMPCLS_LAPTOP            		(BTSDK_DEVCLS_COMPUTER | 0x00000C)
#define BTSDK_COMPCLS_HANDHELD				  	(BTSDK_DEVCLS_COMPUTER | 0x000010)
#define BTSDK_COMPCLS_PALMSIZED					(BTSDK_DEVCLS_COMPUTER | 0x000014)
#define BTSDK_COMPCLS_WEARABLE					(BTSDK_DEVCLS_COMPUTER | 0x000018)

/*the minor device class field - phone major class*/
#define BTSDK_PHONECLS_UNCLASSIFIED   			(BTSDK_DEVCLS_PHONE | 0x000000) 
#define BTSDK_PHONECLS_CELLULAR         		(BTSDK_DEVCLS_PHONE | 0x000004)
#define BTSDK_PHONECLS_CORDLESS        			(BTSDK_DEVCLS_PHONE | 0x000008)
#define BTSDK_PHONECLS_SMARTPHONE    			(BTSDK_DEVCLS_PHONE | 0x00000C)
#define BTSDK_PHONECLS_WIREDMODEM    			(BTSDK_DEVCLS_PHONE | 0x000010)
#define BTSDK_PHONECLS_COMMONISDNACCESS			(BTSDK_DEVCLS_PHONE | 0x000014)
#define BTSDK_PHONECLS_SIMCARDREADER			(BTSDK_DEVCLS_PHONE | 0x000018)

/*the minor device class field - LAN/Network access point major class*/
#define BTSDK_LAP_FULLY             	    	(BTSDK_DEVCLS_LAP | 0x000000)
#define BTSDK_LAP_17              		       	(BTSDK_DEVCLS_LAP | 0x000002)
#define BTSDK_LAP_33              		       	(BTSDK_DEVCLS_LAP | 0x000004)
#define BTSDK_LAP_50                		   	(BTSDK_DEVCLS_LAP | 0x000006)
#define BTSDK_LAP_67              		       	(BTSDK_DEVCLS_LAP | 0x000008)
#define BTSDK_LAP_83              		       	(BTSDK_DEVCLS_LAP | 0x00000A)
#define BTSDK_LAP_99               		      	(BTSDK_DEVCLS_LAP | 0x00000C)
#define BTSDK_LAP_NOSRV       			       	(BTSDK_DEVCLS_LAP | 0x00000D)

/*the minor device class field - Audio/Video major class*/
#define BTSDK_AV_UNCLASSIFIED        		   	(BTSDK_DEVCLS_AUDIO | 0x000000)
#define BTSDK_AV_HEADSET              		  	(BTSDK_DEVCLS_AUDIO | 0x000004)
#define BTSDK_AV_HANDSFREE           		  	(BTSDK_DEVCLS_AUDIO | 0x000008)
#define BTSDK_AV_HEADANDHAND           			(BTSDK_DEVCLS_AUDIO | 0x00000C)
#define BTSDK_AV_MICROPHONE            			(BTSDK_DEVCLS_AUDIO | 0x000010) 
#define BTSDK_AV_LOUDSPEAKER           			(BTSDK_DEVCLS_AUDIO | 0x000014)
#define BTSDK_AV_HEADPHONES            			(BTSDK_DEVCLS_AUDIO | 0x000018)
#define BTSDK_AV_PORTABLEAUDIO     				(BTSDK_DEVCLS_AUDIO | 0x00001C)
#define BTSDK_AV_CARAUDIO          		     	(BTSDK_DEVCLS_AUDIO | 0x000020)
#define BTSDK_AV_SETTOPBOX       		       	(BTSDK_DEVCLS_AUDIO | 0x000024)
#define BTSDK_AV_HIFIAUDIO          		   	(BTSDK_DEVCLS_AUDIO | 0x000028)
#define BTSDK_AV_VCR                     		(BTSDK_DEVCLS_AUDIO | 0x00002C)
#define BTSDK_AV_VIDEOCAMERA      		     	(BTSDK_DEVCLS_AUDIO | 0x000030)
#define BTSDK_AV_CAMCORDER           	  		(BTSDK_DEVCLS_AUDIO | 0x000034)
#define BTSDK_AV_VIDEOMONITOR	        	 	(BTSDK_DEVCLS_AUDIO | 0x000038)
#define BTSDK_AV_VIDEODISPANDLOUDSPK		 	(BTSDK_DEVCLS_AUDIO | 0x00003C) 
#define BTSDK_AV_VIDEOCONFERENCE     	  		(BTSDK_DEVCLS_AUDIO | 0x000040)
#define BTSDK_AV_GAMEORTOY             			(BTSDK_DEVCLS_AUDIO | 0x000048)

/*the minor device class field - peripheral major class*/
#define BTSDK_PERIPHERAL_KEYBOARD			 	(BTSDK_DEVCLS_PERIPHERAL | 0x000040)    
#define BTSDK_PERIPHERAL_POINT			    	(BTSDK_DEVCLS_PERIPHERAL | 0x000080)
#define BTSDK_PERIPHERAL_KEYORPOINT			 	(BTSDK_DEVCLS_PERIPHERAL | 0x0000C0)
#define BTSDK_PERIPHERAL_UNCLASSIFIED			(BTSDK_DEVCLS_PERIPHERAL | 0x000000) 
#define BTSDK_PERIPHERAL_JOYSTICK				(BTSDK_DEVCLS_PERIPHERAL | 0x000004)
#define BTSDK_PERIPHERAL_GAMEPAD				(BTSDK_DEVCLS_PERIPHERAL | 0x000008)
#define BTSDK_PERIPHERAL_REMCONTROL				(BTSDK_DEVCLS_PERIPHERAL | 0x00000C)
#define BTSDK_PERIPHERAL_SENSE				 	(BTSDK_DEVCLS_PERIPHERAL | 0x000010)

/*the minor device class field - imaging major class*/
#define BTSDK_IMAGE_DISPLAY					   	(BTSDK_DEVCLS_IMAGE | 0x000010)
#define BTSDK_IMAGE_CAMERA					   	(BTSDK_DEVCLS_IMAGE | 0x000020)
#define BTSDK_IMAGE_SCANNER					   	(BTSDK_DEVCLS_IMAGE | 0x000040)
#define BTSDK_IMAGE_PRINTER					   	(BTSDK_DEVCLS_IMAGE | 0x000080)

/* Class of Service */
#define BTSDK_CLS_SERIAL_PORT					0x1101
#define BTSDK_CLS_LAN_ACCESS					0x1102
#define BTSDK_CLS_DIALUP_NET					0x1103
#define BTSDK_CLS_IRMC_SYNC						0x1104
#define BTSDK_CLS_OBEX_OBJ_PUSH					0x1105
#define BTSDK_CLS_OBEX_FILE_TRANS				0x1106
#define BTSDK_CLS_IRMC_SYNC_CMD					0x1107
#define BTSDK_CLS_HEADSET						0x1108
#define BTSDK_CLS_CORDLESS_TELE					0x1109
#define BTSDK_CLS_AUDIO_SOURCE					0x110A	
#define BTSDK_CLS_AUDIO_SINK					0x110B
#define BTSDK_CLS_AVRCP_TG						0x110C
#define BTSDK_CLS_ADV_AUDIO_DISTRIB				0x110D
#define BTSDK_CLS_AVRCP_CT						0x110E
#define BTSDK_CLS_VIDEO_CONFERENCE				0x110F
#define BTSDK_CLS_INTERCOM						0x1110
#define BTSDK_CLS_FAX							0x1111
#define BTSDK_CLS_HEADSET_AG					0x1112
#define BTSDK_CLS_WAP							0x1113
#define BTSDK_CLS_WAP_CLIENT					0x1114
#define BTSDK_CLS_PAN_PANU						0x1115
#define BTSDK_CLS_PAN_NAP						0x1116
#define BTSDK_CLS_PAN_GN						0x1117
#define BTSDK_CLS_DIRECT_PRINT					0x1118
#define BTSDK_CLS_REF_PRINT						0x1119
#define BTSDK_CLS_IMAGING						0x111A
#define BTSDK_CLS_IMAG_RESPONDER				0x111B
#define BTSDK_CLS_IMAG_AUTO_ARCH				0x111C
#define BTSDK_CLS_IMAG_REF_OBJ					0x111D
#define BTSDK_CLS_HANDSFREE						0x111E
#define BTSDK_CLS_HANDSFREE_AG					0x111F
#define BTSDK_CLS_HID							0x1124
#define BTSDK_CLS_HCRP							0x1125
#define BTSDK_CLS_HCR_PRINT						0x1126
#define BTSDK_CLS_HCR_SCAN						0x1127
#define BTSDK_CLS_SIM_ACCESS					0x112D
#define BTSDK_CLS_PNP_INFO						0x1200

/* Type of Serial Wrap specific event */ 
#define BTSDK_APP_EV_SWRAP_DRVOPEN						1
#define BTSDK_APP_EV_SWRAP_DRVCLOSE						2

/* Type of Connection Event */
#define BTSDK_APP_EV_CONN						0x01	
#define BTSDK_APP_EV_DISC						0x02	

/* Type of Shortcut Event */
#define BTSDK_SHC_EV_CONN						BTSDK_APP_EV_CONN	
#define BTSDK_SHC_EV_DISC						BTSDK_APP_EV_DISC	

#define BTSDK_APP_EV_BASE						0x100
/* PAN specific event */
#define BTSDK_APP_EV_PAN_BASE					0x100
#define BTSDK_APP_EV_PAN_CONN					(BTSDK_APP_EV_PAN_BASE+0)
#define BTSDK_APP_EV_PAN_DISC					(BTSDK_APP_EV_PAN_BASE+1)
#define BTSDK_APP_EV_PAN_IS_IVTNAP				(BTSDK_APP_EV_PAN_BASE+2) 
#define BTSDK_APP_EV_PAN_NAP_CONFIG				(BTSDK_APP_EV_PAN_BASE+3) 

/* OPP specific event */
#define BTSDK_APP_EV_OPP_BASE				    0x200
#define BTSDK_APP_EV_OPP_CONN					(BTSDK_APP_EV_OPP_BASE+0)
#define BTSDK_APP_EV_OPP_DISC					(BTSDK_APP_EV_OPP_BASE+1)
#define BTSDK_APP_EV_OPP_PULL					(BTSDK_APP_EV_OPP_BASE+2)
#define BTSDK_APP_EV_OPP_PUSH					(BTSDK_APP_EV_OPP_BASE+3)
#define BTSDK_APP_EV_OPP_PUSH_CARD				(BTSDK_APP_EV_OPP_BASE+4)
#define BTSDK_APP_EV_OPP_EXCHG					(BTSDK_APP_EV_OPP_BASE+5)

/* FTP specific event */
#define BTSDK_APP_EV_FTP_BASE					0x300
#define BTSDK_APP_EV_FTP_PUT					(BTSDK_APP_EV_FTP_BASE+0)
#define BTSDK_APP_EV_FTP_GET				    (BTSDK_APP_EV_FTP_BASE+1)
#define BTSDK_APP_EV_FTP_BROWSE					(BTSDK_APP_EV_FTP_BASE+2)
#define BTSDK_APP_EV_FTP_DEL_FILE				(BTSDK_APP_EV_FTP_BASE+3)
#define BTSDK_APP_EV_FTP_DEL_FOLDER				(BTSDK_APP_EV_FTP_BASE+4)	
#define BTSDK_APP_EV_FTP_CREATE					(BTSDK_APP_EV_FTP_BASE+5)
#define BTSDK_APP_EV_FTP_SET_CUR				(BTSDK_APP_EV_FTP_BASE+6)
#define BTSDK_APP_EV_FTP_SET_ROOT				(BTSDK_APP_EV_FTP_BASE+7)
#define BTSDK_APP_EV_FTP_ABORT					(BTSDK_APP_EV_FTP_BASE+8)
#define BTSDK_APP_EV_FTP_BACK					(BTSDK_APP_EV_FTP_BASE+9)
#define BTSDK_APP_EV_FTP_CONN					(BTSDK_APP_EV_FTP_BASE+10)

/* SYNC specific event */
#define BTSDK_APP_EV_SYNC_BASE					0x400
#define BTSDK_APP_EV_SYNC_START					(BTSDK_APP_EV_SYNC_BASE+0)
#define BTSDK_APP_EV_SYNC_CHALOG				(BTSDK_APP_EV_SYNC_BASE+1)
#define BTSDK_APP_EV_SYNC_DEVINFO				(BTSDK_APP_EV_SYNC_BASE+2)
#define BTSDK_APP_EV_SYNC_CC					(BTSDK_APP_EV_SYNC_BASE+3)
#define BTSDK_APP_EV_SYNC_INFOLOG				(BTSDK_APP_EV_SYNC_BASE+4)
#define BTSDK_APP_EV_SYNC_STREAM				(BTSDK_APP_EV_SYNC_BASE+5)
#define BTSDK_APP_EV_SYNC_LUID					(BTSDK_APP_EV_SYNC_BASE+6)
#define BTSDK_APP_EV_SYNC_OK					(BTSDK_APP_EV_SYNC_BASE+7)
#define BTSDK_APP_EV_SYNC_ADD					(BTSDK_APP_EV_SYNC_BASE+8)
#define BTSDK_APP_EV_SYNC_MODIFY				(BTSDK_APP_EV_SYNC_BASE+9)
#define BTSDK_APP_EV_SYNC_DELETE				(BTSDK_APP_EV_SYNC_BASE+10)
#define BTSDK_APP_EV_SYNC_PREV_CHALOG			(BTSDK_APP_EV_SYNC_BASE+11)


/* HCRP specific event */
#define BTSDK_APP_EV_HCRP_BASE					0x500
#define BTSDK_APP_EV_HCRP_NOTIF					(BTSDK_APP_EV_HCRP_BASE+1)
#define BTSDK_APP_EV_HCRP_REG_NOTIF				(BTSDK_APP_EV_HCRP_BASE+2)
#define BTSDK_APP_EV_HCRP_GET_LPTSTAT			(BTSDK_APP_EV_HCRP_BASE+3)
#define BTSDK_APP_EV_HCRP_GET_1284ID			(BTSDK_APP_EV_HCRP_BASE+4)
#define BTSDK_APP_EV_HCRP_SOFT_RESET			(BTSDK_APP_EV_HCRP_BASE+5)
#define BTSDK_APP_EV_HCRP_HARD_RESET			(BTSDK_APP_EV_HCRP_BASE+6)
#define BTSDK_APP_EV_HCRP_DATA					(BTSDK_APP_EV_HCRP_BASE+7)
#define BTSDK_APP_EV_HCRP_RECEIVE_DATA			(BTSDK_APP_EV_HCRP_BASE+8)
#define BTSDK_APP_EV_HCRP_SEND_DATA				(BTSDK_APP_EV_HCRP_BASE+9)


/* HID specific event */
#define BTSDK_APP_EV_HID_BASE 					0x600
#define BTSDK_APP_EV_HID_CONN					(BTSDK_APP_EV_HID_BASE+1)
#define BTSDK_APP_EV_HID_UNPLUG					(BTSDK_APP_EV_HID_BASE+2)

/* BIP specific event */
#define BTSDK_APP_EV_BIP_BASE					0x700
#define BTSDK_APP_EV_BIP_START_ARCHIVE			(BTSDK_APP_EV_BIP_BASE+0)
#define BTSDK_APP_EV_BIP_ADV_PRINT				(BTSDK_APP_EV_BIP_BASE+1)
#define BTSDK_APP_EV_BIP_START_PRINT			(BTSDK_APP_EV_BIP_BASE+2)
#define BTSDK_APP_EV_BIP_GET_MON				(BTSDK_APP_EV_BIP_BASE+3)
#define BTSDK_APP_EV_BIP_STORE_IMG				(BTSDK_APP_EV_BIP_BASE+4)
#define BTSDK_APP_EV_BIP_REM_DISP				(BTSDK_APP_EV_BIP_BASE+5)
#define BTSDK_APP_EV_BIP_CONN					(BTSDK_APP_EV_BIP_BASE+6)
#define BTSDK_APP_EV_BIP_DISCONN				(BTSDK_APP_EV_BIP_BASE+7)
#define BTSDK_APP_EV_BIP_ABORT					(BTSDK_APP_EV_BIP_BASE+8)
#define BTSDK_APP_EV_BIP_NORMAL					(BTSDK_APP_EV_BIP_BASE+9)

/* CTP specific event */
#define BTSDK_APP_EV_CTPICP_BASE 				0x800
#define BTSDK_APP_EV_CTPICP_ATTACH				(BTSDK_APP_EV_CTPICP_BASE + 1)
#define BTSDK_APP_EV_CTPICP_DETACH				(BTSDK_APP_EV_CTPICP_BASE + 2)
#define BTSDK_APP_EV_CTPICP_CTPRING				(BTSDK_APP_EV_CTPICP_BASE + 3)
#define BTSDK_APP_EV_CTPICP_CTPREGRING			(BTSDK_APP_EV_CTPICP_BASE + 4)
#define BTSDK_APP_EV_CTPICP_ICPRING				(BTSDK_APP_EV_CTPICP_BASE + 5)
#define BTSDK_APP_EV_CTPICP_HANGUP				(BTSDK_APP_EV_CTPICP_BASE + 6)
#define BTSDK_APP_EV_CTPICP_ACTIVE				(BTSDK_APP_EV_CTPICP_BASE + 7)
#define BTSDK_APP_EV_CTPICP_CCID				(BTSDK_APP_EV_CTPICP_BASE + 8)
#define BTSDK_APP_EV_CTPICP_TLADDED				(BTSDK_APP_EV_CTPICP_BASE + 9)
#endif

/* HSP/HFP AG specific event. */
#define BTSDK_APP_EV_AGAP_BASE 							 0x900
#define BTSDK_APP_EV_AGAP_STATE_CHANGED_IND              (BTSDK_APP_EV_AGAP_BASE + 0x01)
#define BTSDK_APP_EV_AGAP_RMT_RELEASE_CALL_IND           (BTSDK_APP_EV_AGAP_BASE + 0x02)
#define BTSDK_APP_EV_AGAP_RMT_IS_BUSY_IND                (BTSDK_APP_EV_AGAP_BASE + 0x03)
#define BTSDK_APP_EV_AGAP_HF_AVAILABLE_IND               (BTSDK_APP_EV_AGAP_BASE + 0x04)
#define BTSDK_APP_EV_AGAP_HF_UNAVAILABLE_IND             (BTSDK_APP_EV_AGAP_BASE + 0x05)
#define BTSDK_APP_EV_AGAP_VOICE_RECOG_ACTIVATE_REQ       (BTSDK_APP_EV_AGAP_BASE + 0x41)
#define BTSDK_APP_EV_AGAP_VOICE_RECOG_DEACTIVATE_REQ     (BTSDK_APP_EV_AGAP_BASE + 0x42)
#define BTSDK_APP_EV_AGAP_INCOMINGCALL_ANSWERED_IND      (BTSDK_APP_EV_AGAP_BASE + 0x43)
#define BTSDK_APP_EV_AGAP_CALL_CANCELED_IND              (BTSDK_APP_EV_AGAP_BASE + 0x44)
#define BTSDK_APP_EV_AGAP_AUDIO_CONN_ESTABLISHED_IND     (BTSDK_APP_EV_AGAP_BASE + 0x45)
#define BTSDK_APP_EV_AGAP_AUDIO_CONN_RELEASED_IND        (BTSDK_APP_EV_AGAP_BASE + 0x46)
#define BTSDK_APP_EV_AGAP_CUR_INDICATOR_VAL_REQ          (BTSDK_APP_EV_AGAP_BASE + 0x47)
#define BTSDK_APP_EV_AGAP_DTMF_IND                       (BTSDK_APP_EV_AGAP_BASE + 0x48)
#define BTSDK_APP_EV_AGAP_SPKVOL_CHANGED_IND             (BTSDK_APP_EV_AGAP_BASE + 0x49)
#define BTSDK_APP_EV_AGAP_VOICETAG_PHONE_NUM_REQ         (BTSDK_APP_EV_AGAP_BASE + 0x4a)
#define BTSDK_APP_EV_AGAP_HF_DIAL_IND                    (BTSDK_APP_EV_AGAP_BASE + 0x4b)
#define BTSDK_APP_EV_AGAP_HF_MEM_DIAL_IND                (BTSDK_APP_EV_AGAP_BASE + 0x4c)
#define BTSDK_APP_EV_AGAP_HF_LASTNUM_REDIAL_IND          (BTSDK_APP_EV_AGAP_BASE + 0x4d)
#define BTSDK_APP_EV_AGAP_NREC_DISENABLE_IND             (BTSDK_APP_EV_AGAP_BASE + 0x4e)
#define BTSDK_APP_EV_AGAP_GENERATE_INBAND_RINGTONE_IND   (BTSDK_APP_EV_AGAP_BASE + 0x4f)
#define BTSDK_APP_EV_AGAP_TERMINATE_INBAND_RINGTONE_IND  (BTSDK_APP_EV_AGAP_BASE + 0x50)
#define BTSDK_APP_EV_AGAP_EXTEND_CMD_IND                 (BTSDK_APP_EV_AGAP_BASE + 0x51)
#define BTSDK_APP_EV_AGAP_NETWORK_AVAILABLE_IND          (BTSDK_APP_EV_AGAP_BASE + 0x52)
#define BTSDK_APP_EV_AGAP_NETWORK_UNAVAILABLE_IND        (BTSDK_APP_EV_AGAP_BASE + 0x53)
#define BTSDK_APP_EV_AGAP_PAIRED_DEV_HDL_REQ			 (BTSDK_APP_EV_AGAP_BASE + 0x54) 

/* HSP/HFP specific event. */
#define BTSDK_APP_EV_HFAP_BASE 							0xA00
#define BTSDK_APP_EV_HFAP_RINGING_IND                   (BTSDK_APP_EV_HFAP_BASE + 0x01)
#define BTSDK_APP_EV_HFAP_HANGUP_IND                    (BTSDK_APP_EV_HFAP_BASE + 0x02)
#define BTSDK_APP_EV_HFAP_OUTGOINGCALL_IND              (BTSDK_APP_EV_HFAP_BASE + 0x03)
#define BTSDK_APP_EV_HFAP_ONGOINGCALL_IND               (BTSDK_APP_EV_HFAP_BASE + 0x04)
#define BTSDK_APP_EV_HFAP_AG_AVAILABLE_IND              (BTSDK_APP_EV_HFAP_BASE + 0x05)
#define BTSDK_APP_EV_HFAP_AG_UNAVAILABLE_IND            (BTSDK_APP_EV_HFAP_BASE + 0x06)
#define BTSDK_APP_EV_HFAP_CLI_IND                       (BTSDK_APP_EV_HFAP_BASE + 0x41)
#define BTSDK_APP_EV_HFAP_SPKVOL_CHANGED_IND            (BTSDK_APP_EV_HFAP_BASE + 0x42)
#define BTSDK_APP_EV_HFAP_VOICETAG_PHONE_NUM_RSP        (BTSDK_APP_EV_HFAP_BASE + 0x44)
#define BTSDK_APP_EV_HFAP_VOICE_RECOGN_ACTIVATED_IND    (BTSDK_APP_EV_HFAP_BASE + 0x45)
#define BTSDK_APP_EV_HFAP_VOICE_RECOGN_DEACTIVATED_IND  (BTSDK_APP_EV_HFAP_BASE + 0x46)
#define BTSDK_APP_EV_HFAP_TERMINATE_LOCAL_RINGTONE_IND  (BTSDK_APP_EV_HFAP_BASE + 0x47)
#define BTSDK_APP_EV_HFAP_CALL_WAITING_NOTIF            (BTSDK_APP_EV_HFAP_BASE + 0x48)
#define BTSDK_APP_EV_HFAP_EXTEND_CMD_IND                (BTSDK_APP_EV_HFAP_BASE + 0x49)
#define BTSDK_APP_EV_HFAP_NETWORK_UNAVAILABLE_IND       (BTSDK_APP_EV_HFAP_BASE + 0x4a)
#define BTSDK_APP_EV_HFAP_NETWORK_AVAILABLE_IND         (BTSDK_APP_EV_HFAP_BASE + 0x4b)
#define BTSDK_APP_EV_HFAP_EXTEND_FUNC_ENABLED_IND       (BTSDK_APP_EV_HFAP_BASE + 0x4c)
#define BTSDK_APP_EV_HFAP_EXTEND_FUNC_DISENABLED_IND    (BTSDK_APP_EV_HFAP_BASE + 0x4d)
#define BTSDK_APP_EV_HFAP_REPEAT_CONN_START_IND         (BTSDK_APP_EV_HFAP_BASE + 0x4e)
#define BTSDK_APP_EV_HFAP_REPEAT_CONN_TERMINATE_IND     (BTSDK_APP_EV_HFAP_BASE + 0x4f)
#define BTSDK_APP_EV_HFAP_SCO_CONN_IND                  (BTSDK_APP_EV_HFAP_BASE + 0x50)
#define BTSDK_APP_EV_HFAP_SCO_DISC_IND                  (BTSDK_APP_EV_HFAP_BASE + 0x51)
