/***************************************************************************
 *
 *                      Pollex Mobile Platform
 *
 * Copyright (c) 2004 by Pollex Mobile Software Co., Ltd. 
 *                       All Rights Reserved 
 *
 * Module   : 
 *
 * Purpose  : 
 *
\**************************************************************************/
#ifndef _SMS_RS_H_
#define _SMS_RS_H_

#define IDS_EXIT                    ML("Exit")
#define IDS_SEND                    ML("Send")
#define IDS_SENDWITHCOORDINATES     ML("Send with coordinates")
#define IDS_ADDRECIPIENT            ML("Add recipient")
#define IDS_INSERTTEMPLATE          ML("Insert template")
#define IDS_MSGINFO                 ML("Message info")
#define IDS_CENTREINUSE             ML("Msg. Centre in use")
#define IDS_REPORT                  ML("Report reception")
#define IDS_VALIDITY                ML("Message validity")
#define IDS_SENTAS                  ML("Message type")
#define IDS_REPLYPATH               ML("Keep reply center")
#define IDS_OPTIONS                 ML("Send with options")
#define IDS_REPLY                   ML("Reply")
#define IDS_FORWARD                 ML("Forward")
#define IDS_CALL                    ML("Call")
#define IDS_DELETE                  ML("Delete")
#define IDS_DETAIL                  ML("Message details")
#define IDS_MOVE                    ML("Move to folder...")
#define IDS_CONTACTS                ML("Add to contacts")
#define IDS_PHONE                   ML("Phone")
#define IDS_EMAILADDRESS            ML("Email address")
#define IDS_EMAIL                   ML("E-mail")
#define IDS_WEB                     ML("Web address")
#define IDS_FIND                    ML("Find")
#define IDS_FROM                    ML("From ex")
#define IDS_TO                      ML("To ex")
#define IDS_SMS                     ML("SMS")
#define IDS_OK                      ML("OK")
#define IDS_RECIPIENT               ML("Recipient")
#define IDS_SUBJECT                 ML("Subject ex")
#define IDS_DATE                    ML("Date ex")
#define IDS_TIME                    ML("Time ex")
#define IDS_TYPE                    ML("Type ex")
#define IDS_COPYTOFOLDER            ML("Copy to forlder")
#define IDS_COPYTOINBOX             ML("Inbox")
#define IDS_COPYTOMYFOLDER          ML("My folders")
#define IDS_OPEN                    ML("Open")
#define IDS_WAITING                 ML("Please waiting...")
#define IDS_SIMMSG                  ML("SIM messages")
#define IDS_NORECORD				ML("No messages")
#define IDS_NOSIMCARD               ML("No SIM card!")
#define IDS_DELETEFAIL              ML("Delete failed!")
#define IDS_SCAINUSE                ML("Msg. Centre in use")
#define IDS_YES                     ML("Yes")
#define IDS_NO                      ML("No")
#define IDS_1HOUR                   ML("An hour")
#define IDS_6HOURS                  ML("Six hours")
#define IDS_1DAY                    ML("24 hours")
#define IDS_3DAYS                   ML("Three days")
#define IDS_1WEEK                   ML("A week")
#define IDS_MAXTIME                 ML("Maximum time")
#define IDS_TEXT                    ML("Text")
#define IDS_FAX                     ML("Fax")
#define IDS_PAGE                    ML("Page")
#define IDS_SENDASEMAIL             ML("E-mail")
#define IDS_GSM                     ML("GSM")
#define IDS_GPRS                    ML("GPRS")
#define IDS_NULL                    ML("None")
#define IDS_CANCEL                  ML("Cancel")
#define IDS_SCA                     ML("Message centres")
#define IDS_CONNECTION              ML("Bearer")
#define IDS_EDIT                    ML("Edit")
#define IDS_NEWSCA                  ML("New msg. Centre")
#define IDS_SCANAME                 ML("Msg. centre name")
#define IDS_SCANUM                  ML("Msg. Centre number")
#define IDS_SMSSETTING              ML("SMS")
#define IDS_FILLNAME                ML("Please input Msg. centre name!")
#define IDS_FILLNUM                 ML("Please input Msg. centre number!")
#define IDS_NAMESAME                ML("Msg. centre name is same!")
#define IDS_WARNING                 ML("Warning")
#define IDS_SELSCA                  ML("Select Msg. centre")
#define IDS_CHANGE                  ML("Change")
#define IDS_CB                      ML("Cell broadcasts")
#define IDS_SUBSCRIBE               ML("Subscribe")
#define IDS_UNSUBSCRIBE             ML("Unsubscribe")
#define IDS_HOTMARK                 ML("Hotmark")
#define IDS_REMOVEHOTMARK           ML("Remove hotmark")
#define IDS_ADDMAUALLY              ML("Add manually")
#define IDS_DELALL                  ML("Delete all")
#define IDS_TOPIC                   ML("Topic")
#define IDS_CBSETTING               ML("Settings")
#define IDS_RECEPTION               ML("Reception")
#define IDS_ON                      ML("On")
#define IDS_OFF                     ML("Off")
#define IDS_ALL                     ML("All")
#define IDS_SELECTION               ML("Selection")
#define IDS_OTHER                   ML("Other")
#define IDS_TOPICNAME               ML("Topic name")
#define IDS_TOPICNUM                ML("Topic number")
#define IDS_COPY                    ML("Copy")
#define IDS_NEEDFRAG                ML("Parts in message: %d. Send anyway")
#define IDS_VCARD                   ML("Vcard")
#define IDS_VCAL                    ML("Vcal")
#define IDS_SAVE                    ML("Save")
#define IDS_SAVETODRAFTS            ML("Save to Drafts")
#define IDS_PASTE                   ML("Paste")
#define IDS_SAVE2DRAFTS             ML("Save to Drafts ex")
#define IDS_MESSAGESENT             ML("Message sent")
#define IDS_SAVEDTODRAFT            ML("Saved to Drafts")
#define IDS_DRAFTFULL               ML("Drafts full.Message not saved.")
#define IDS_GOTOURL                 ML("Go to URL")
#define IDS_ADDTOBOOKMARK           ML("Add to bookmarks")
#define IDS_VIEWONMAP               ML("View on map")
#define IDS_SETASDESTINATION        ML("Set as destination")
#define IDS_SAVEASWAYPOINT          ML("Save as waypoint")
#define IDS_UPDATEEXISTING          ML("Update existing")
#define IDS_CREATENEW               ML("Create new")
#define IDS_ADDTOCONTACTS           ML("Add to contacts")
#define IDS_HIDEFOUNDITEMS          ML("Hide found items")
#define IDS_COORDINATE              ML("Coordinates")
#define IDS_MMS                     ML("MMS")
#define IDS_PHONENO                 ML("Phone number")
#define IDS_DELETEMESSAGE           ML("Delete message")
#define IDS_SIZE                    ML("Size ex")
#define IDS_SELECT                  ML("Select")
#define IDS_ALL                     ML("All")
#define IDS_DELETEMANY              ML("Delete many")
#define IDS_MESSAGECOPIED           ML("Message copied")
#define IDS_SIMSCA                  ML("SIM Msg. Centre")
#define IDS_SIMSCAN                 ML("SIM Msg. Centre %d")
#define IDS_SENDING                 ML("Sending")
#define IDS_COPYING                 ML("Copying")
#define IDS_DELETING                ML("Deleting")
#define IDS_DELETEALL               ML("Delete all ex")
#define IDS_NEWSMS                  ML("New SMS")
#define IDS_BACK                    ML("Back")
#define IDS_NONETWORK               ML("No network.Sending failed.")
#define IDS_SENDINGFAILED           ML("Sending failed.")
#define IDS_INVALIDNUM              ML("Invalid phone number. Sending failed.")
#define IDS_INITING                 ML("SMS Init,please waiting...")
#define IDS_SAVEVCARD               ML("Save business card")
#define IDS_SAVEVCAL                ML("Save calendar entry")
#define IDS_ACTIVATE                ML("Activate")
#define IDS_NEWSMSPROFILE           ML("New SMS profile")
#define IDS_SMSPROFILENAME          ML("SMS profile name")
#define IDS_SMSCENTERNR             ML("SMS center nr")
#define IDS_SMSPROFILE              ML("SMS profile")
#define IDS_ACTIVATED               ML("Activated")
#define IDS_SETCENTERNR             ML("SMS center nr not set. Set now")
#define IDS_DELETEDACTIVE           ML("Delete active profile")
#define IDS_LASTDELETE              ML("Last profile. Delete anyway")
#define IDS_DELETED                 ML("Deleted")
#define IDS_VOICEMAILBOX            ML("Voice mailbox")
#define IDS_VOICEMAILBOXNR          ML("Voice mailbox nr ex")
#define IDS_LANGUAGES               ML("Languages")
#define IDS_TOPICDETECTION          ML("Topic detection")
#define IDS_SELECTED                ML("Selected")
#define IDS_SELECTLANGUAGES         ML("Select language(s)")
#define IDS_ADD                     ML("Add")
#define IDS_CONFIRM                 ML("Confirm")
#define IDS_CALLTO                  ML("Call to")
#define IDS_PLSSELECTMSGS           ML("Please select messages")
#define IDS_DELSEL                  ML("Delete selected messages ex")
#define IDS_DELIVERYSTATUS          ML("Delivery status")
#define IDS_PENDING                 ML("Pending")
#define IDS_DELIVERED               ML("Delivered")
#define IDS_FAILED                  ML("Failed")
#define IDS_REPORTTITLE             ML("Report")
#define IDS_ADDTOPIC                ML("Add topic")
#define IDS_TOPICNR                 ML("Topic number")
#define IDS_MOVED                   ML("Moved")
#define IDS_DEFINENAME              ML("Please define name")
#define IDS_OVERSIZE                ML("SMS too large. Please remove text.")
#define IDS_SAVEDTOCONTACT          ML("Saved to Contacts")
#define IDS_MESSAGING               ML("Messaging")
#define IDS_SAVEDTOCALENDAR         ML("Saved to Calendar")
#define IDS_WRITEMEASSAGE           ML("Write message")
#define IDS_SAVETOCONTACTS          ML("Save to Contacts")
#define IDS_NOMORETOPICALLOW        ML("No more topics allowed")
#define IDS_NOMATCHESFOUND          ML("No matches found")
#define IDS_TOPICEXISTS             ML("Topic already exists")
#define IDS_GERMAN                  ML("German")
#define IDS_ENGLISH                 ML("English")
#define IDS_ITALIAN                 ML("Italian")
#define IDS_FRENCH                  ML("French")
#define IDS_SPANISH                 ML("Spanish")
#define IDS_DUTCH                   ML("Dutch")
#define IDS_SWEDISH                 ML("Swedish")
#define IDS_DANISH                  ML("Danish")
#define IDS_PORTUGUESE              ML("Portuguese")
#define IDS_FINNISH                 ML("Finnish")
#define IDS_NORWEGIAN               ML("Norwegian")
#define IDS_GREEK                   ML("Greek")
#define IDS_TURKISH                 ML("Turkish")
#define IDS_HUNGARIAN               ML("Hungarian")
#define IDS_POLISH                  ML("Polish")
#define IDS_OPENING                 ML("Opening...")
#define IDS_SELECTTEMPLATE          ML("Select Template")
#define IDS_WRITE                   ML("Write message")
#define IDS_DEFINENUM               ML("Please define number")
#define IDS_SENDFAILEDNOSIM         ML("Sending failed. No SIM card")
#define IDS_PLSDEFINELANG           ML("Please define language")
#define IDS_EDITTOPIC               ML("Edit topic")
#define IDS_DELETETOPIC             ML("Delete topic")

#endif // _SMS_RS_H_
