/***************************************************************************
 *
 *                      Pollex Mobile Platform
 *
 * Copyright (c) 2004 by Pollex Mobile Software Co., Ltd. 
 *                       All Rights Reserved 
 *
 * Module   : 
 *
 * Purpose  : 
 *
\**************************************************************************/
#ifndef _MU_RS_H_
#define _MU_RS_H_

#define IDS_EXIT                ML("Exit")
#define IDS_WARNING             ML("Warning")
#define IDS_PROMPT              ML("Prompt")
#define IDS_OPEN                ML("Open")
#define IDS_SMS                 ML("SMS")
#define IDS_MMS                 ML("MMS")
#define IDS_EMAIL               ML("E-mail")
#define IDS_CREATEMSG           ML("Create message")
#define IDS_TOSENDER            ML("To sender")
#define IDS_TOALL               ML("To all")
#define IDS_REPLY               ML("Reply")
#define IDS_DELETE              ML("Delete")
#define IDS_DETAIL              ML("Message info")
#define IDS_MOVETOFOLDER        ML("Move to folder")
#define IDS_MOVETODRAFTS        ML("Move to drafts")
#define IDS_DEFER               ML("Defer sending")
#define IDS_SEND                ML("Send")
#define IDS_CALL                ML("Call")
#define IDS_INBOX               ML("Inbox")
#define IDS_OUTBOX              ML("Outbox")
#define IDS_SENT                ML("Sent")
#define IDS_DRAFT               ML("Drafts")
#define IDS_DELIVERYREPORT      ML("Reports")
#define IDS_MYFOLDER            ML("My folders")
#define IDS_SIMMSG              ML("SIM messages")
#define IDS_CELLBROADCAST       ML("Cell broadcast")
#define IDS_CALLVOICEMAILBOX    ML("Call voice mailbox")
#define IDS_SETTING             ML("Setting")
#define IDS_NEW                 ML("New message")
#define IDS_SELECTFOLDER        ML("Select folder")
#define IDS_OK                  ML("OK")
#define IDS_CANCEL              ML("Cancel")
#define IDS_NEWFOLDER           ML("New folder")
#define IDS_RENAMEFOLDER        ML("Rename")
#define IDS_DELETEFOLDER        ML("Delete")
#define IDS_PHRASE              ML("Phrase")
#define IDS_FOLDERNAME          ML("Folder name")
#define IDS_FOLDERNAMETEMP1     ML("Folder")
#define IDS_FOLDERNAMETEMP2     ML("Folder %d")
#define IDS_CONFIRM             ML("Confirm")
#define IDS_WAITING             ML("Waiting")
#define IDS_MESSAGING           ML("Messaging")
#define IDS_TEMPLATES           ML("Templates")
#define IDS_CB                  ML("Cell broadcast")
#define IDS_NOMESSAGES          ML("No messages")
#define IDS_MOVEMANY            ML("Move many")
#define IDS_EDIT                ML("Edit")
#define IDS_MSGINFO             ML("Message info")
#define IDS_SELECT              ML("Select")
#define IDS_ALL                 ML("All")
#define IDS_DELETEMANY          ML("Delete many")
#define IDS_FORWARD             ML("Forward")
#define IDS_SUSPEND             ML("Suspend")
#define IDS_REMOVEALL           ML("Remove all")
#define IDS_SELECTFOLDER        ML("Select folder")
#define IDS_PENDING				ML("Pending")
#define IDS_DELIEVED			ML("Delivered")
#define IDS_FAILED				ML("Failed")

#define IDS_READSMSFAILED       ML("Read SMS failed!")
#define IDS_READMMSFAILED       ML("Read MMS failed!")
#define IDS_READEMAILBOXFAILED  ML("Read Emailbox failed!")
#define IDS_READEMAILFAILED     ML("Read Email failed!")
#define IDS_READPUSHFAILED      ML("Read Push failed!")
#define IDS_DELSMSERR           ML("Delete SMS error!")
#define IDS_DELSMSFAILED        ML("Delete SMS failed!")
#define IDS_DELMMSERR           ML("Delete MMS error!")
#define IDS_DELMMSFAILED        ML("Delete MMS failed!")
#define IDS_DELEMAILERR         ML("Delete Email error!")
#define IDS_DELEMAILFAILED      ML("Delete Email failed!")
#define IDS_DELPUSHERR          ML("Delete Push error!")
#define IDS_DELPUSHFAILED       ML("Delete Push failed!")
#define IDS_CHANGESTATEFAILED   ML("Change state failed!")
#define IDS_ERR_LOWMEMORY       ML("Low Memory")
#define IDS_ERR_SMS             ML("SMS error")
#define IDS_ERR_MMS             ML("MMS error")
#define IDS_ERR_EMAIL           ML("Email error")
#define IDS_ERR_PUSH            ML("Push error")
#define IDS_FOLDERNAMEUSED      ML("Folder name is used!")
#define IDS_DELFOLDERERR        ML("Delete Folder error!")
#define IDS_DELFOLDERFAILED     ML("Delete Folder failed!")
#define IDS_SUREDEL             ML("Delete message")
#define IDS_INITING             ML("SMS Init,please waiting...")
#define IDS_BACK                ML("Back")
#define IDS_SAVE                ML("Save")


#define IDS_DELETE_ALL			ML("Delete all ex")
#define IDS_DELETEING			ML("Deleting...")
#define IDS_DELETED				ML("Deleted")
#define IDS_DELSEL				ML("Delete selected messages ex")
#define IDS_SEL_MESSAGE			ML("Please select messages")
#define IDS_MOVING				ML("Moving messages...")
#define IDS_MESSAGES_MOVED		ML("Messages moved")
#define IDS_MESSAGES_MOVED_TODRAFT	ML("Message moved to Drafts")
#define IDS_MOVE				ML("Move")
#define IDS_MSG_WAITING			ML("Waiting")
#define IDS_MSG_SENDING			ML("Sending")
#define IDS_MSG_FAILED			ML("Failed")
#define IDS_MSG_SUSPENDED		ML("Suspended")
#define IDS_SURE_DELFOLDER		ML("Delete Folder and contents")
#define IDS_NO_REPORTS			ML("No reports")
#define IDS_DAIL_TO				ML("Call to ex")
#define IDS_YES					ML("Yes")
#define IDS_NO					ML("No")
#define IDS_RENAME_FOLDER		ML("Rename folder")
#define IDS_REMOVE_REPORT		ML("Remove all reports ex")
#define IDS_INSERT_SIM			ML("insert sim card")

#define IDS_DEFINENAME          ML("Define name")
#endif // _MU_RS_H_
