/***************************************************************************
 *
 *                      Pollex Mobile Platform
 *
 * Copyright (c) 2004 by Pollex Mobile Software Co., Ltd. 
 *                       All Rights Reserved 
 *
 * Module   : 
 *
 * Purpose  : 
 *
\**************************************************************************/

GetSystemTime

SetSystemTime
GetLocalTime
SetLocalTime
SystemTimeToTzSpecificLocalTime
GetTimeZoneInformation
SetTimeZoneInformation
GetTickCount
GetLastError
SetLastError
RegisterResource
UnregisterResource
FindResource
LoadResource
LockResource
FreeResource
LoadImage
IsDBCSLeadByte
LoadString
LoadStringPtr
MultiByteToWideChar
WideCharToMultiByte
MultiByteToUTF8
UTF8ToMultiByte
GSMToMultiByte
MultiByteToGSM
IsGSMCode
IsGSMString
GetSysColor
SetSysColors
CreateDC
CreateScreenDC
CreateCompatibleDC
CreateMemoryDC
DeleteDC
CreatePrinterDC
StartDoc
EndDoc
StartPage
EndPage
StartBand
EndBand
SetTextColor
GetTextColor
SetBkColor
GetBkColor
SetTextAlign
GetTextAlign
SetBkMode
GetBkMode
SetROP2
GetROP2
GetDeviceCaps
SetMapMode
GetMapMode
SetWindowOrgEx
GetWindowOrgEx
SetWindowExtEx
GetWindowExtEx
OffsetWindowOrgEx
ScaleWindowExtEx
SetViewportExtEx
GetViewportExtEx
SetViewportOrgEx
GetViewportOrgEx
OffsetViewportOrgEx
ScaleViewportExtEx
DPtoLP
LPtoDP
SetClipRect
GetStockObject
DeleteObject
SelectObject
GetObject
UnrealizeObject
CreatePen
CreatePenIndirect
CreateBrush
CreateSolidBrush
CreateHatchBrush
CreatePatternBrush
CreateBrushIndirect
SetBrushOrg
CreateRectRgn
CreateRectRgnIndirect
SetRectRgn
CombineRgn
EqualRgn
OffsetRgn
GetRgnBox
RectInRegion
PtInRegion
SelectClipRgn
ExtSelectClipRgn
GetClipBox
IntersectClipRect
OffsetClipRgn
ExcludeClipRect
PtVisible
RectVisible
SetPixel
GetPixel
DrawLine
DrawRect
ClearRect
DrawCircle
Ellipse
AngleArc
Arc
ArcTo
Chord
Pie
Polygon
SetArcDirection
GetArcDirection
MoveToEx
GetCurrentPositionEx
LineTo
Rectangle
RoundRect
FillRect
FrameRect
InvertRect
SetDefaultChar
TextOut
GetTextExtentPoint
GetTextExtentExPoint
DrawText
CreateFont
CreateFontIndirect
GetTextMetrics
CreateBitmap
CreateBitmapEx
CreateBitmapIndirect
CreateCompatibleBitmap
CreateDIBitmap
LoadBitmap
LoadImageEx
PatBlt
BitBlt
StretchBlt
SetBitmapBits
SetDIBits
GetDIBits
SetDIBitsToDevice
StretchDIBits
AlphaBlend
AlphaDIBBlend
TransparentBlt
TransparentDIBits
DrawBitmapFromData
DrawBitmapFromFile
GetSystemMetrics
SetRect
SetRectEmpty
CopyRect
IsRectEmpty
EqualRect
IntersectRect
UnionRect
SubtractRect
OffsetRect
InflateRect
PtInRect
PtInRectXY
NormalizeRect
GetMessage
PostMessage
PostThreadMessage
SendMessage
SendNotifyMessage
PostQuitMessage
TranslateMessage
DispatchMessage
PeekMessage
RegisterClassBase
RegisterClassExBase
RegisterClass
RegisterClassEx
UnregisterClass
GetClassInfo
GetClassName
GetClassWord
SetClassWord
GetClassLong
SetClassLong
IsWindow
CreateWindow
CreateWindowEx
DestroyWindow
IsChild
GetParent
GetWindowExtraDataPtrBase
GetWindowExtraDataPtr
GetUserData
GetDesktopWindow
IsWindowVisible
ShowWindow
EnableWindow
IsWindowEnabled
SetWindowText
GetWindowText
GetWindowTextLength
GetWindowWord
SetWindowWord
GetWindowLong
SetWindowLong
GetClientRect
GetWindowRect
GetWindowRectEx
MoveWindow
MoveWindowToTop
StartDrag
EndDrag
DrawDragFrame
DefWindowProcBase
DefWindowProc
CallWindowProc
ShowOwnedPopups
ClientToScreen
ScreenToClient
WindowFromPoint
ChildWindowFromPoint
FindWindow
EnumWindows
EnumChildWindows
GetWindow
GetDC
ReleaseDC
GetWindowDC
GetUpdateRect
BeginPaint
EndPaint
UpdateWindow
InvalidateRect
ValidateRect
ScrollWindow
GetWindowThreadProcessId
SetForegroundWindow
GetForegroundWindow
SetActiveWindow
GetActiveWindow
GetFocus
SetFocus
GrabKeyboard
UngrabKeyboard
SendChar
SendKeyDown
SendKeyUp
GetKeyboardState
ToAscii
RegisterLongKey
UnregisterLongKey
BeginPenCalibrate
EndPenCalibrate
SetPointDevScale
SetCapture
ReleaseCapture
GetCapture
FlushInputMessages
GetSysModalWindow
SetSysModalWindow
SetTimer
KillTimer
IsMenu
CreateMenu
CreatePopupMenu
LoadMenu
LoadMenuIndirect
DestroyMenu
GetMenu
SetMenu
DrawMenuBar
HiliteMenuItem
InsertMenu
AppendMenu
ModifyMenu
RemoveMenu
DeleteMenu
ChangeMenu
EnableMenuItem
CheckMenuItem
GetSubMenu
GetMenuItemCount
GetMenuItemID
GetMenuString
GetMenuState
SetMenuItemBitmaps
GetMenuCheckMarkDimensions
TrackPopupMenu
SetScrollInfo
GetScrollInfo
EnableScrollBar
OpenClipboard
CloseClipboard
EmptyClipboard
SetClipboardData
GetClipboardData
IsClipboardFormatAvailable
RegisterClipboardFormat
GetClipboardFormatName
LoadCursor
CreateCursor
DestroyCursor
ShowCursor
SetCursor
SetCursorPos
GetCursorPos
ClipCursor
GetClipCursor
SetMaxCursorRect
BeginWaitCursor
EndWaitCursor
LoadIcon
CreateIcon
DestroyIcon
GetIconDimension
GetIconDimensionFromFile
DrawIcon
DrawIconFromFile
DrawIconFromFileEx
MessageBox
MessageBeep
CreateCaret
DestroyCaret
SetCaretPos
GetCaretPos
HideCaret
ShowCaret
GetCaretBlinkTime
SetCaretBlinkTime
IsDialogMessage
IsInputMessage
DefDlgProc
CreateDialog
CreateDialogIndirect
CreateDialogParam
CreateDialogIndirectParam
DialogBox
DialogBoxIndirect
DialogBoxParam
DialogBoxIndirectParam
EndDialog
GetDlgCtrlID
GetDlgItem
SendDlgItemMessage
SetDlgItemText
GetDlgItemText
CheckDlgButton
CheckRadioButton
IsDlgButtonChecked
GetNextDlgGroupItem
GetNextDlgTabItem
SetWindowsHookEx
UnhookWindowsHookEx
CallNextHookEx
ChangeDisplaySettings
EnumDisplaySettings
UpdateScreen
